name: Feature Request
description: Suggest an idea for LoFi Player
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
  - type: textarea
    attributes:
      label: Solution/Idea
      description: Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        Please include a list of what the feature should and shouldn't do by filling in the table below.

        'Must' implies that the feature should not ship without this capability.
        'Should' is something we should push hard for, but is not absolutely required to ship.
        'Could' is a nice-to-have; a good stretch goal that isn't painful if we don't achieve it.
        'Won't' is a clear statement that the proposal/feature will intentionally not have that capability.

        This list will evolve and grow as the proposal becomes more refined over time.
        A good rule of thumb is to start your proposal with no more than 7 high-level requirements.
  - type: textarea
    attributes:
      label: Priorities
      description: Describe all the elements of the idea and how important they are.
      value: |
        | Capability | Priority |
        | :---------- | :------- |
        | This proposal will allow developers to accomplish W | Must |
        | This proposal will allow end users to accomplish X | Should |
        | This proposal will allow developers to accomplish Y | Could |
        | This proposal will allow end users to accomplish Z | Won't |
  - type: input
    id: app-version
    attributes:
      label: LoFi Player Version
      description: What version of LoFi Player are you using?
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System Version
      description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
      placeholder: e.g. Windows 10 21H1, macOS Catalina 10.15.7, or Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional comment
      description: Add any other comment or screenshots about the feature request here.